"""Error code definitions used across the API.

This module only defines error codes that are currently referenced in the
codebase. Unused or legacy codes were removed to keep the enumeration concise
and maintainable.
"""

from enum import Enum


class ErrorCode(str, Enum):
    """Application-wide error codes."""

    # Authentication & validation
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"
    BAD_REQUEST = "BAD_REQUEST"
    NOT_FOUND = "NOT_FOUND"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    RESET_TOKEN_INVALID = "RESET_TOKEN_INVALID"

    PASSWORD_MISMATCH = "PASSWORD_MISMATCH"
    PASSWORD_MUST_BE_AT_LEAST_6_CHARACTERS = (
        "PASSWORD_MUST_BE_AT_LEAST_6_CHARACTERS"
    )
    PASSWORD_MUST_NOT_CONTAIN_SPACES = "PASSWORD_MUST_NOT_CONTAIN_SPACES"
    WRONG_PASSWORD = "WRONG_PASSWORD"
    USERNAME_MUST_BE_AT_LEAST_6_CHARACTERS = (
        "USERNAME_MUST_BE_AT_LEAST_6_CHARACTERS"
    )
    USERNAME_MUST_NOT_CONTAIN_SPACES = "USERNAME_MUST_NOT_CONTAIN_SPACES"
    EMAIL_DOMAIN_NOT_ALLOWED = "EMAIL_DOMAIN_NOT_ALLOWED"
    INVALID_INPUT_DATA = "INVALID_INPUT_DATA"

    # User & Account
    EMAIL_EXISTS = "EMAIL_EXISTS"
    USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED"
    USER_NOT_VERIFIED = "USER_NOT_VERIFIED"
    USER_NAME_REQUIRED = "USER_NAME_REQUIRED"
    USERNAME_EXISTS = "USERNAME_EXISTS"
    USER_NOT_FOUND = "USER_NOT_FOUND"

    # Role & Permission
    TAC_NHAN_NOT_FOUND = "TAC_NHAN_NOT_FOUND"
    TEN_TAC_NHAN_EXISTS = "TEN_TAC_NHAN_EXISTS"
    QUYEN_HAN_NOT_FOUND = "QUYEN_HAN_NOT_FOUND"
    TEN_QUYEN_HAN_EXISTS = "TEN_QUYEN_HAN_EXISTS"
    QUYEN_HAN_IN_USE = "QUYEN_HAN_IN_USE"

    # Image assets
    IMAGE_ASSET_NOT_FOUND = "IMAGE_ASSET_NOT_FOUND"
    IMAGE_ASSET_CODE_EXISTS = "IMAGE_ASSET_CODE_EXISTS"
    IMAGE_ASSET_INVALID_ID = "IMAGE_ASSET_INVALID_ID"
    IMAGE_ASSET_EMPTY_UPDATE = "IMAGE_ASSET_EMPTY_UPDATE"
    IMAGE_ASSET_FILE_REQUIRED = "IMAGE_ASSET_FILE_REQUIRED"
    IMAGE_ASSET_FILE_TYPE_NOT_ALLOWED = "IMAGE_ASSET_FILE_TYPE_NOT_ALLOWED"
    IMAGE_ASSET_IMAGE_OPTIMIZE_FAILED = "IMAGE_ASSET_IMAGE_OPTIMIZE_FAILED"
    IMAGE_ASSET_IMAGE_NOT_FOUND = "IMAGE_ASSET_IMAGE_NOT_FOUND"
    IMAGE_ASSET_STORAGE_ERROR = "IMAGE_ASSET_STORAGE_ERROR"

    # Image search
    IMAGE_SEARCH_FILE_REQUIRED = "IMAGE_SEARCH_FILE_REQUIRED"
    IMAGE_SEARCH_FILE_TYPE_NOT_ALLOWED = "IMAGE_SEARCH_FILE_TYPE_NOT_ALLOWED"
    IMAGE_SEARCH_INVALID_IMAGE = "IMAGE_SEARCH_INVALID_IMAGE"
    IMAGE_SEARCH_INDEX_NOT_FOUND = "IMAGE_SEARCH_INDEX_NOT_FOUND"
    IMAGE_SEARCH_DEPENDENCY_MISSING = "IMAGE_SEARCH_DEPENDENCY_MISSING"
    IMAGE_SEARCH_PROCESSING_FAILED = "IMAGE_SEARCH_PROCESSING_FAILED"
